services:
  - type: web
    name: solar-lms
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /healthz
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: solar-db
          property: connectionString
      - key: PORT
        value: "8080"
      - key: Jwt__Secret
        generateValue: true
      - key: SEQ_SERVER_URL
        fromService:
          type: web
          name: solar-seq
          property: host

  - type: web
    name: solar-seq
    env: image
    image:
      url: datalust/seq:latest
    plan: free
    region: oregon
    envVars:
      - key: ACCEPT_EULA
        value: "Y"
      - key: SEQ_FIRSTRUN_NOAUTHENTICATION
        value: "true"
      - key: PORT
        value: "80"

databases:
  - name: solar-db
    plan: free
    databaseName: solar_development
    user: solar
    region: oregon
